apiVersion: v1
kind: ConfigMap
metadata:
  name: stage-ti-backend-configmap
  namespace: stage
data:
  SMS_URL: https://japi.instaalerts.zone/httpapi/QueryStringReceiver?ver="{version}"&key="{key}"&dest=91"{mobilenumber}"&send="{send}"&text="{smstext}"
  SMS_VERSION: '1.0'
  EMAIL_SMTP_PROTOCOL: smtp
  EMAIL_SMTP_PORT: '587'
  WEBSITE_RESET_URL: https://appconsole.trackandtrail.in
  GOOGLE_STORAGE_URL: https://storage.googleapis.com/
  GOOGLE_STORAGE_BUCKET_NAME: ti-mobile-backend-app-asia-st1-bucket
  FILE_UPLOAD_SIZE: '20'
  
